### ISSUE TITLE
Rate Limiting

### ISSUE THREAD

**Issue by wutmikee** [iamstarkov/get-twitter-followers#5]
Hey - looks like a cool package. How does it factor in rate limiting?

**Comment by iamstarkov** [comment]
this package is using these endpoints:
- `followers/ids` ([usage](https://github.com/iamstarkov/get-twitter-followers/blob/master/index.js#L16), [api](https://dev.twitter.com/rest/reference/get/followers/ids)) offers `5000` ids per req and allows to do 15 of them, which leads us up to `75 000 (5000 * 15)` fetched followers ids.
- `users/lookup` ([usage](https://github.com/iamstarkov/get-twitter-followers/blob/master/index.js#L6), [api](https://dev.twitter.com/rest/reference/get/users/lookup)), offers `100` users objects per req and allows to do 180 requests, which leads us up to `18 000 (100 * 180)` user objects.

So `get-twitter-followers` can fetch 75k followers' ids, but only able to saturate only 18k of them.

**Comment by iamstarkov** [comment]
question was answered, so i closed an issue
