### ISSUE TITLE
How this should work?

### ISSUE THREAD

**Issue by sidan5** [iamstarkov/get-twitter-followers#6]
I mean what does it do to get followers? I tried to run it and got huge log but nothing happens actually...

**Comment by iamstarkov** [comment]
did you get Twitter API tokens?

**Comment by iamstarkov** [comment]
recipe is here https://iamstarkov.com/get-twitter-tokens/

**Comment by sidan5** [comment]
Did. Ran for a second and nothing happens...

**Comment by iamstarkov** [comment]
ok, what are you trying to achieve and how do you do it?

**Comment by sidan5** [comment]
More followers...

**Comment by iamstarkov** [comment]
@sidan5 show me the code

**Comment by iamstarkov** [comment]
> More followers...

this package is not supposed to do that, its supposed to retrieve your current followers list
